version: '3.9'

services:

  # ------------------------
  # BASE DATOS MC1
  # ------------------------
  db_auth:
    image: postgres:15
    container_name: db_auth
    restart: always
    environment:
      POSTGRES_DB: db_auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - db_auth_data:/var/lib/postgresql/data

  # ------------------------
  # BASE DATOS MC2
  # ------------------------
  db_trans:
    image: postgres:15
    container_name: db_trans
    restart: always
    environment:
      POSTGRES_DB: db_trans
      POSTGRES_USER: trans
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - db_trans_data:/var/lib/postgresql/data


  # ------------------------
  # MICROSERVICIO 1
  # ------------------------
  microservicio-auth:
    build: ./microservicio-auth
    container_name: microservicio-auth
    restart: always
    env_file:
      - ./microservicio-auth/.env
    depends_on:
      - db_auth
    ports:
      - "8001:8001"


  # # ------------------------
  # # MICROSERVICIO 2
  # # ------------------------
  microservicio-trans:
    build: ./microservicio-trans
    container_name: microservicio-trans
    restart: always
    env_file:
      - ./microservicio-trans/.env
    depends_on:
      - db_trans
    ports:
      - "8003:8003"


  # # ------------------------
  # # KONG API GATEWAY
  # # ------------------------
  kong:
    image: kong:3.4
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000" # Proxy
      - "8002:8001" # Admin API
    volumes:
      - ./kong/kong.yml:/kong/kong.yml


volumes:
  db_auth_data:
  db_trans_data:
